modLoader="javafml"
loaderVersion="[30,)"

issueTrackerURL="https://github.com/SquidDev-CC/CC-Tweaked/issues"
displayURL="https://github.com/SquidDev-CC/CC-Tweaked"
logoFile="pack.png"

credits="Created by Daniel Ratcliffe (@DanTwoHundred)"
authors="Daniel Ratcliffe, Aaron Mills, SquidDev"
license="ComputerCraft Public License (https://raw.githubusercontent.com/dan200/ComputerCraft/master/LICENSE)"

[[mods]]
modId="ttoolkittest"
version="1.0.0"
displayName="CC: Tweaked test framework"
description='''
A test framework for ensuring PP works correctly. Copied from CC:T code
'''
